<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{


    protected function authenticate($request, $guards)
    {

        return parent::authenticate($request, ['web','api']); // TODO: Change the autogenerated stub
    }

    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            if ($request->is('api/*')) {
                return route('unAuthenticated');
            }
            return route('login');
        }
    }
}
