<?php
/**
 * Auto generated
 * User: rupertlustosa
 * Email: rupertlustosa@gmail.com
 * Date: 15/07/14
 * Time: 14:37
 */

use App\Models\City;
use Illuminate\Database\Seeder;

class CityDevSeeder extends Seeder
{
    public function run()
    {
        $cities = array(
            array(
                "id" => 2200053,
                "state_id" => 22,
                "city" => "Acauã",
                "lat" => -8.219540,
                "lng" => -41.083099,
                "capital" => 0,
            ),
            array(
                "id" => 2200103,
                "state_id" => 22,
                "city" => "Agricolândia",
                "lat" => -5.796760,
                "lng" => -42.666401,
                "capital" => 0,
            ),
            array(
                "id" => 2200202,
                "state_id" => 22,
                "city" => "Água Branca",
                "lat" => -5.888560,
                "lng" => -42.637001,
                "capital" => 0,
            ),
            array(
                "id" => 2200251,
                "state_id" => 22,
                "city" => "Alagoinha do Piauí",
                "lat" => -7.000390,
                "lng" => -40.928200,
                "capital" => 0,
            ),
            array(
                "id" => 2200277,
                "state_id" => 22,
                "city" => "Alegrete do Piauí",
                "lat" => -7.241960,
                "lng" => -40.856602,
                "capital" => 0,
            ),
            array(
                "id" => 2200301,
                "state_id" => 22,
                "city" => "Alto Longá",
                "lat" => -5.256340,
                "lng" => -42.209599,
                "capital" => 0,
            ),
            array(
                "id" => 2200400,
                "state_id" => 22,
                "city" => "Altos",
                "lat" => -5.038880,
                "lng" => -42.461201,
                "capital" => 0,
            ),
            array(
                "id" => 2200459,
                "state_id" => 22,
                "city" => "Alvorada do Gurguéia",
                "lat" => -8.424180,
                "lng" => -43.777000,
                "capital" => 0,
            ),
            array(
                "id" => 2200509,
                "state_id" => 22,
                "city" => "Amarante",
                "lat" => -6.243040,
                "lng" => -42.843300,
                "capital" => 0,
            ),
            array(
                "id" => 2200608,
                "state_id" => 22,
                "city" => "Angical do Piauí",
                "lat" => -6.087860,
                "lng" => -42.740002,
                "capital" => 0,
            ),
            array(
                "id" => 2200707,
                "state_id" => 22,
                "city" => "Anísio de Abreu",
                "lat" => -9.185640,
                "lng" => -43.049400,
                "capital" => 0,
            ),
            array(
                "id" => 2200806,
                "state_id" => 22,
                "city" => "Antônio Almeida",
                "lat" => -7.212760,
                "lng" => -44.188900,
                "capital" => 0,
            ),
            array(
                "id" => 2200905,
                "state_id" => 22,
                "city" => "Aroazes",
                "lat" => -6.110220,
                "lng" => -41.782200,
                "capital" => 0,
            ),
            array(
                "id" => 2200954,
                "state_id" => 22,
                "city" => "Aroeiras do Itaim",
                "lat" => -7.245020,
                "lng" => -41.532501,
                "capital" => 0,
            ),
            array(
                "id" => 2201002,
                "state_id" => 22,
                "city" => "Arraial",
                "lat" => -6.650750,
                "lng" => -42.541801,
                "capital" => 0,
            ),
            array(
                "id" => 2201051,
                "state_id" => 22,
                "city" => "Assunção do Piauí",
                "lat" => -5.865000,
                "lng" => -41.038898,
                "capital" => 0,
            ),
            array(
                "id" => 2201101,
                "state_id" => 22,
                "city" => "Avelino Lopes",
                "lat" => -10.134500,
                "lng" => -43.956299,
                "capital" => 0,
            ),
            array(
                "id" => 2201150,
                "state_id" => 22,
                "city" => "Baixa Grande do Ribeiro",
                "lat" => -7.849030,
                "lng" => -45.219002,
                "capital" => 0,
            ),
            array(
                "id" => 2201176,
                "state_id" => 22,
                "city" => "Barra D'Alcântara",
                "lat" => -6.516450,
                "lng" => -42.114601,
                "capital" => 0,
            ),
            array(
                "id" => 2201200,
                "state_id" => 22,
                "city" => "Barras",
                "lat" => -4.244680,
                "lng" => -42.292198,
                "capital" => 0,
            ),
            array(
                "id" => 2201309,
                "state_id" => 22,
                "city" => "Barreiras do Piauí",
                "lat" => -9.929600,
                "lng" => -45.470200,
                "capital" => 0,
            ),
            array(
                "id" => 2201408,
                "state_id" => 22,
                "city" => "Barro Duro",
                "lat" => -5.816730,
                "lng" => -42.514702,
                "capital" => 0,
            ),
            array(
                "id" => 2201507,
                "state_id" => 22,
                "city" => "Batalha",
                "lat" => -4.022300,
                "lng" => -42.078701,
                "capital" => 0,
            ),
            array(
                "id" => 2201556,
                "state_id" => 22,
                "city" => "Bela Vista do Piauí",
                "lat" => -7.988090,
                "lng" => -41.867500,
                "capital" => 0,
            ),
            array(
                "id" => 2201572,
                "state_id" => 22,
                "city" => "Belém do Piauí",
                "lat" => -7.366520,
                "lng" => -40.968800,
                "capital" => 0,
            ),
            array(
                "id" => 2201606,
                "state_id" => 22,
                "city" => "Beneditinos",
                "lat" => -5.456760,
                "lng" => -42.363800,
                "capital" => 0,
            ),
            array(
                "id" => 2201705,
                "state_id" => 22,
                "city" => "Bertolínia",
                "lat" => -7.633380,
                "lng" => -43.949799,
                "capital" => 0,
            ),
            array(
                "id" => 2201739,
                "state_id" => 22,
                "city" => "Betânia do Piauí",
                "lat" => -8.143760,
                "lng" => -40.798901,
                "capital" => 0,
            ),
            array(
                "id" => 2201770,
                "state_id" => 22,
                "city" => "Boa Hora",
                "lat" => -4.414040,
                "lng" => -42.135700,
                "capital" => 0,
            ),
            array(
                "id" => 2201804,
                "state_id" => 22,
                "city" => "Bocaina",
                "lat" => -6.941240,
                "lng" => -41.316799,
                "capital" => 0,
            ),
            array(
                "id" => 2201903,
                "state_id" => 22,
                "city" => "Bom Jesus",
                "lat" => -9.071240,
                "lng" => -44.359001,
                "capital" => 0,
            ),
            array(
                "id" => 2201919,
                "state_id" => 22,
                "city" => "Bom Princípio do Piauí",
                "lat" => -3.196310,
                "lng" => -41.640301,
                "capital" => 0,
            ),
            array(
                "id" => 2201929,
                "state_id" => 22,
                "city" => "Bonfim do Piauí",
                "lat" => -9.160500,
                "lng" => -42.886501,
                "capital" => 0,
            ),
            array(
                "id" => 2201945,
                "state_id" => 22,
                "city" => "Boqueirão do Piauí",
                "lat" => -4.481810,
                "lng" => -42.121201,
                "capital" => 0,
            ),
            array(
                "id" => 2201960,
                "state_id" => 22,
                "city" => "Brasileira",
                "lat" => -4.133700,
                "lng" => -41.785900,
                "capital" => 0,
            ),
            array(
                "id" => 2201988,
                "state_id" => 22,
                "city" => "Brejo do Piauí",
                "lat" => -8.203140,
                "lng" => -42.822899,
                "capital" => 0,
            ),
            array(
                "id" => 2202000,
                "state_id" => 22,
                "city" => "Buriti dos Lopes",
                "lat" => -3.182590,
                "lng" => -41.869499,
                "capital" => 0,
            ),
            array(
                "id" => 2202026,
                "state_id" => 22,
                "city" => "Buriti dos Montes",
                "lat" => -5.305840,
                "lng" => -41.093300,
                "capital" => 0,
            ),
            array(
                "id" => 2202059,
                "state_id" => 22,
                "city" => "Cabeceiras do Piauí",
                "lat" => -4.477300,
                "lng" => -42.306900,
                "capital" => 0,
            ),
            array(
                "id" => 2202075,
                "state_id" => 22,
                "city" => "Cajazeiras do Piauí",
                "lat" => -6.796670,
                "lng" => -42.390301,
                "capital" => 0,
            ),
            array(
                "id" => 2202083,
                "state_id" => 22,
                "city" => "Cajueiro da Praia",
                "lat" => -2.931110,
                "lng" => -41.340801,
                "capital" => 0,
            ),
            array(
                "id" => 2202091,
                "state_id" => 22,
                "city" => "Caldeirão Grande do Piauí",
                "lat" => -7.331400,
                "lng" => -40.636600,
                "capital" => 0,
            ),
            array(
                "id" => 2202109,
                "state_id" => 22,
                "city" => "Campinas do Piauí",
                "lat" => -7.659300,
                "lng" => -41.877499,
                "capital" => 0,
            ),
            array(
                "id" => 2202117,
                "state_id" => 22,
                "city" => "Campo Alegre do Fidalgo",
                "lat" => -8.382360,
                "lng" => -41.834400,
                "capital" => 0,
            ),
            array(
                "id" => 2202133,
                "state_id" => 22,
                "city" => "Campo Grande do Piauí",
                "lat" => -7.128270,
                "lng" => -41.031502,
                "capital" => 0,
            ),
            array(
                "id" => 2202174,
                "state_id" => 22,
                "city" => "Campo Largo do Piauí",
                "lat" => -3.804410,
                "lng" => -42.639999,
                "capital" => 0,
            ),
            array(
                "id" => 2202208,
                "state_id" => 22,
                "city" => "Campo Maior",
                "lat" => -4.821700,
                "lng" => -42.164101,
                "capital" => 0,
            ),
            array(
                "id" => 2202251,
                "state_id" => 22,
                "city" => "Canavieira",
                "lat" => -7.688210,
                "lng" => -43.723301,
                "capital" => 0,
            ),
            array(
                "id" => 2202307,
                "state_id" => 22,
                "city" => "Canto do Buriti",
                "lat" => -8.111100,
                "lng" => -42.951698,
                "capital" => 0,
            ),
            array(
                "id" => 2202406,
                "state_id" => 22,
                "city" => "Capitão de Campos",
                "lat" => -4.457000,
                "lng" => -41.944000,
                "capital" => 0,
            ),
            array(
                "id" => 2202455,
                "state_id" => 22,
                "city" => "Capitão Gervásio Oliveira",
                "lat" => -8.496550,
                "lng" => -41.813999,
                "capital" => 0,
            ),
            array(
                "id" => 2202505,
                "state_id" => 22,
                "city" => "Caracol",
                "lat" => -9.279330,
                "lng" => -43.328999,
                "capital" => 0,
            ),
            array(
                "id" => 2202539,
                "state_id" => 22,
                "city" => "Caraúbas do Piauí",
                "lat" => -3.475250,
                "lng" => -41.842499,
                "capital" => 0,
            ),
            array(
                "id" => 2202554,
                "state_id" => 22,
                "city" => "Caridade do Piauí",
                "lat" => -7.734350,
                "lng" => -40.984798,
                "capital" => 0,
            ),
            array(
                "id" => 2202604,
                "state_id" => 22,
                "city" => "Castelo do Piauí",
                "lat" => -5.318690,
                "lng" => -41.549900,
                "capital" => 0,
            ),
            array(
                "id" => 2202653,
                "state_id" => 22,
                "city" => "Caxingó",
                "lat" => -3.419040,
                "lng" => -41.895500,
                "capital" => 0,
            ),
            array(
                "id" => 2202703,
                "state_id" => 22,
                "city" => "Cocal",
                "lat" => -3.472790,
                "lng" => -41.554600,
                "capital" => 0,
            ),
            array(
                "id" => 2202711,
                "state_id" => 22,
                "city" => "Cocal de Telha",
                "lat" => -4.557100,
                "lng" => -41.958698,
                "capital" => 0,
            ),
            array(
                "id" => 2202729,
                "state_id" => 22,
                "city" => "Cocal dos Alves",
                "lat" => -3.620470,
                "lng" => -41.440201,
                "capital" => 0,
            ),
            array(
                "id" => 2202737,
                "state_id" => 22,
                "city" => "Coivaras",
                "lat" => -5.092240,
                "lng" => -42.208000,
                "capital" => 0,
            ),
            array(
                "id" => 2202752,
                "state_id" => 22,
                "city" => "Colônia do Gurguéia",
                "lat" => -8.183700,
                "lng" => -43.793999,
                "capital" => 0,
            ),
            array(
                "id" => 2202778,
                "state_id" => 22,
                "city" => "Colônia do Piauí",
                "lat" => -7.226510,
                "lng" => -42.175598,
                "capital" => 0,
            ),
            array(
                "id" => 2202802,
                "state_id" => 22,
                "city" => "Conceição do Canindé",
                "lat" => -7.876380,
                "lng" => -41.594200,
                "capital" => 0,
            ),
            array(
                "id" => 2202851,
                "state_id" => 22,
                "city" => "Coronel José Dias",
                "lat" => -8.813970,
                "lng" => -42.523201,
                "capital" => 0,
            ),
            array(
                "id" => 2202901,
                "state_id" => 22,
                "city" => "Corrente",
                "lat" => -10.433300,
                "lng" => -45.163300,
                "capital" => 0,
            ),
            array(
                "id" => 2203008,
                "state_id" => 22,
                "city" => "Cristalândia do Piauí",
                "lat" => -10.644300,
                "lng" => -45.189301,
                "capital" => 0,
            ),
            array(
                "id" => 2203107,
                "state_id" => 22,
                "city" => "Cristino Castro",
                "lat" => -8.822730,
                "lng" => -44.223000,
                "capital" => 0,
            ),
            array(
                "id" => 2203206,
                "state_id" => 22,
                "city" => "Curimatá",
                "lat" => -10.032600,
                "lng" => -44.300201,
                "capital" => 0,
            ),
            array(
                "id" => 2203230,
                "state_id" => 22,
                "city" => "Currais",
                "lat" => -9.011750,
                "lng" => -44.406200,
                "capital" => 0,
            ),
            array(
                "id" => 2203255,
                "state_id" => 22,
                "city" => "Curralinhos",
                "lat" => -5.608250,
                "lng" => -42.837601,
                "capital" => 0,
            ),
            array(
                "id" => 2203271,
                "state_id" => 22,
                "city" => "Curral Novo do Piauí",
                "lat" => -7.831300,
                "lng" => -40.895699,
                "capital" => 0,
            ),
            array(
                "id" => 2203305,
                "state_id" => 22,
                "city" => "Demerval Lobão",
                "lat" => -5.358750,
                "lng" => -42.677601,
                "capital" => 0,
            ),
            array(
                "id" => 2203354,
                "state_id" => 22,
                "city" => "Dirceu Arcoverde",
                "lat" => -9.339390,
                "lng" => -42.434799,
                "capital" => 0,
            ),
            array(
                "id" => 2203404,
                "state_id" => 22,
                "city" => "Dom Expedito Lopes",
                "lat" => -6.953320,
                "lng" => -41.639599,
                "capital" => 0,
            ),
            array(
                "id" => 2203420,
                "state_id" => 22,
                "city" => "Domingos Mourão",
                "lat" => -4.249500,
                "lng" => -41.268299,
                "capital" => 0,
            ),
            array(
                "id" => 2203453,
                "state_id" => 22,
                "city" => "Dom Inocêncio",
                "lat" => -9.005160,
                "lng" => -41.969700,
                "capital" => 0,
            ),
            array(
                "id" => 2203503,
                "state_id" => 22,
                "city" => "Elesbão Veloso",
                "lat" => -6.199470,
                "lng" => -42.135502,
                "capital" => 0,
            ),
            array(
                "id" => 2203602,
                "state_id" => 22,
                "city" => "Eliseu Martins",
                "lat" => -8.096290,
                "lng" => -43.670502,
                "capital" => 0,
            ),
            array(
                "id" => 2203701,
                "state_id" => 22,
                "city" => "Esperantina",
                "lat" => -3.888630,
                "lng" => -42.232399,
                "capital" => 0,
            ),
            array(
                "id" => 2203750,
                "state_id" => 22,
                "city" => "Fartura do Piauí",
                "lat" => -9.483420,
                "lng" => -42.791199,
                "capital" => 0,
            ),
            array(
                "id" => 2203800,
                "state_id" => 22,
                "city" => "Flores do Piauí",
                "lat" => -7.787930,
                "lng" => -42.917999,
                "capital" => 0,
            ),
            array(
                "id" => 2203859,
                "state_id" => 22,
                "city" => "Floresta do Piauí",
                "lat" => -7.466820,
                "lng" => -41.788300,
                "capital" => 0,
            ),
            array(
                "id" => 2203909,
                "state_id" => 22,
                "city" => "Floriano",
                "lat" => -6.771820,
                "lng" => -43.024101,
                "capital" => 0,
            ),
            array(
                "id" => 2204006,
                "state_id" => 22,
                "city" => "Francinópolis",
                "lat" => -6.393340,
                "lng" => -42.259102,
                "capital" => 0,
            ),
            array(
                "id" => 2204105,
                "state_id" => 22,
                "city" => "Francisco Ayres",
                "lat" => -6.626060,
                "lng" => -42.688099,
                "capital" => 0,
            ),
            array(
                "id" => 2204154,
                "state_id" => 22,
                "city" => "Francisco Macedo",
                "lat" => -7.331000,
                "lng" => -40.787998,
                "capital" => 0,
            ),
            array(
                "id" => 2204204,
                "state_id" => 22,
                "city" => "Francisco Santos",
                "lat" => -6.994910,
                "lng" => -41.128799,
                "capital" => 0,
            ),
            array(
                "id" => 2204303,
                "state_id" => 22,
                "city" => "Fronteiras",
                "lat" => -7.081730,
                "lng" => -40.614601,
                "capital" => 0,
            ),
            array(
                "id" => 2204352,
                "state_id" => 22,
                "city" => "Geminiano",
                "lat" => -7.154760,
                "lng" => -41.340900,
                "capital" => 0,
            ),
            array(
                "id" => 2204402,
                "state_id" => 22,
                "city" => "Gilbués",
                "lat" => -9.830010,
                "lng" => -45.342300,
                "capital" => 0,
            ),
            array(
                "id" => 2204501,
                "state_id" => 22,
                "city" => "Guadalupe",
                "lat" => -6.782850,
                "lng" => -43.559399,
                "capital" => 0,
            ),
            array(
                "id" => 2204550,
                "state_id" => 22,
                "city" => "Guaribas",
                "lat" => -9.386470,
                "lng" => -43.694302,
                "capital" => 0,
            ),
            array(
                "id" => 2204600,
                "state_id" => 22,
                "city" => "Hugo Napoleão",
                "lat" => -5.988600,
                "lng" => -42.559799,
                "capital" => 0,
            ),
            array(
                "id" => 2204659,
                "state_id" => 22,
                "city" => "Ilha Grande",
                "lat" => -2.857740,
                "lng" => -41.818600,
                "capital" => 0,
            ),
            array(
                "id" => 2204709,
                "state_id" => 22,
                "city" => "Inhuma",
                "lat" => -6.665000,
                "lng" => -41.704102,
                "capital" => 0,
            ),
            array(
                "id" => 2204808,
                "state_id" => 22,
                "city" => "Ipiranga do Piauí",
                "lat" => -6.824210,
                "lng" => -41.738098,
                "capital" => 0,
            ),
            array(
                "id" => 2204907,
                "state_id" => 22,
                "city" => "Isaías Coelho",
                "lat" => -7.735970,
                "lng" => -41.673500,
                "capital" => 0,
            ),
            array(
                "id" => 2205003,
                "state_id" => 22,
                "city" => "Itainópolis",
                "lat" => -7.443360,
                "lng" => -41.468700,
                "capital" => 0,
            ),
            array(
                "id" => 2205102,
                "state_id" => 22,
                "city" => "Itaueira",
                "lat" => -7.599890,
                "lng" => -43.024899,
                "capital" => 0,
            ),
            array(
                "id" => 2205151,
                "state_id" => 22,
                "city" => "Jacobina do Piauí",
                "lat" => -7.930630,
                "lng" => -41.207500,
                "capital" => 0,
            ),
            array(
                "id" => 2205201,
                "state_id" => 22,
                "city" => "Jaicós",
                "lat" => -7.362290,
                "lng" => -41.137100,
                "capital" => 0,
            ),
            array(
                "id" => 2205250,
                "state_id" => 22,
                "city" => "Jardim do Mulato",
                "lat" => -6.099000,
                "lng" => -42.630001,
                "capital" => 0,
            ),
            array(
                "id" => 2205276,
                "state_id" => 22,
                "city" => "Jatobá do Piauí",
                "lat" => -4.770250,
                "lng" => -41.817001,
                "capital" => 0,
            ),
            array(
                "id" => 2205300,
                "state_id" => 22,
                "city" => "Jerumenha",
                "lat" => -7.091280,
                "lng" => -43.503300,
                "capital" => 0,
            ),
            array(
                "id" => 2205359,
                "state_id" => 22,
                "city" => "João Costa",
                "lat" => -8.507360,
                "lng" => -42.426399,
                "capital" => 0,
            ),
            array(
                "id" => 2205409,
                "state_id" => 22,
                "city" => "Joaquim Pires",
                "lat" => -3.501640,
                "lng" => -42.186501,
                "capital" => 0,
            ),
            array(
                "id" => 2205458,
                "state_id" => 22,
                "city" => "Joca Marques",
                "lat" => -3.480400,
                "lng" => -42.425499,
                "capital" => 0,
            ),
            array(
                "id" => 2205508,
                "state_id" => 22,
                "city" => "José de Freitas",
                "lat" => -4.751460,
                "lng" => -42.574600,
                "capital" => 0,
            ),
            array(
                "id" => 2205516,
                "state_id" => 22,
                "city" => "Juazeiro do Piauí",
                "lat" => -5.174590,
                "lng" => -41.697601,
                "capital" => 0,
            ),
            array(
                "id" => 2205524,
                "state_id" => 22,
                "city" => "Júlio Borges",
                "lat" => -10.322500,
                "lng" => -44.238098,
                "capital" => 0,
            ),
            array(
                "id" => 2205532,
                "state_id" => 22,
                "city" => "Jurema",
                "lat" => -9.219920,
                "lng" => -43.133701,
                "capital" => 0,
            ),
            array(
                "id" => 2205540,
                "state_id" => 22,
                "city" => "Lagoinha do Piauí",
                "lat" => -5.830740,
                "lng" => -42.622299,
                "capital" => 0,
            ),
            array(
                "id" => 2205557,
                "state_id" => 22,
                "city" => "Lagoa Alegre",
                "lat" => -4.515390,
                "lng" => -42.630901,
                "capital" => 0,
            ),
            array(
                "id" => 2205565,
                "state_id" => 22,
                "city" => "Lagoa do Barro do Piauí",
                "lat" => -8.476730,
                "lng" => -41.534199,
                "capital" => 0,
            ),
            array(
                "id" => 2205573,
                "state_id" => 22,
                "city" => "Lagoa de São Francisco",
                "lat" => -4.385050,
                "lng" => -41.596901,
                "capital" => 0,
            ),
            array(
                "id" => 2205581,
                "state_id" => 22,
                "city" => "Lagoa do Piauí",
                "lat" => -5.418640,
                "lng" => -42.643700,
                "capital" => 0,
            ),
            array(
                "id" => 2205599,
                "state_id" => 22,
                "city" => "Lagoa do Sítio",
                "lat" => -6.507660,
                "lng" => -41.565300,
                "capital" => 0,
            ),
            array(
                "id" => 2205607,
                "state_id" => 22,
                "city" => "Landri Sales",
                "lat" => -7.259220,
                "lng" => -43.936401,
                "capital" => 0,
            ),
            array(
                "id" => 2205706,
                "state_id" => 22,
                "city" => "Luís Correia",
                "lat" => -2.884380,
                "lng" => -41.664101,
                "capital" => 0,
            ),
            array(
                "id" => 2205805,
                "state_id" => 22,
                "city" => "Luzilândia",
                "lat" => -3.468300,
                "lng" => -42.371799,
                "capital" => 0,
            ),
            array(
                "id" => 2205854,
                "state_id" => 22,
                "city" => "Madeiro",
                "lat" => -3.486240,
                "lng" => -42.498100,
                "capital" => 0,
            ),
            array(
                "id" => 2205904,
                "state_id" => 22,
                "city" => "Manoel Emídio",
                "lat" => -8.012340,
                "lng" => -43.875500,
                "capital" => 0,
            ),
            array(
                "id" => 2205953,
                "state_id" => 22,
                "city" => "Marcolândia",
                "lat" => -7.441690,
                "lng" => -40.660198,
                "capital" => 0,
            ),
            array(
                "id" => 2206001,
                "state_id" => 22,
                "city" => "Marcos Parente",
                "lat" => -7.115650,
                "lng" => -43.892601,
                "capital" => 0,
            ),
            array(
                "id" => 2206050,
                "state_id" => 22,
                "city" => "Massapê do Piauí",
                "lat" => -7.474690,
                "lng" => -41.110298,
                "capital" => 0,
            ),
            array(
                "id" => 2206100,
                "state_id" => 22,
                "city" => "Matias Olímpio",
                "lat" => -3.714920,
                "lng" => -42.550701,
                "capital" => 0,
            ),
            array(
                "id" => 2206209,
                "state_id" => 22,
                "city" => "Miguel Alves",
                "lat" => -4.168570,
                "lng" => -42.896301,
                "capital" => 0,
            ),
            array(
                "id" => 2206308,
                "state_id" => 22,
                "city" => "Miguel Leão",
                "lat" => -5.680770,
                "lng" => -42.743599,
                "capital" => 0,
            ),
            array(
                "id" => 2206357,
                "state_id" => 22,
                "city" => "Milton Brandão",
                "lat" => -4.682950,
                "lng" => -41.417301,
                "capital" => 0,
            ),
            array(
                "id" => 2206407,
                "state_id" => 22,
                "city" => "Monsenhor Gil",
                "lat" => -5.562000,
                "lng" => -42.607498,
                "capital" => 0,
            ),
            array(
                "id" => 2206506,
                "state_id" => 22,
                "city" => "Monsenhor Hipólito",
                "lat" => -6.992750,
                "lng" => -41.026001,
                "capital" => 0,
            ),
            array(
                "id" => 2206605,
                "state_id" => 22,
                "city" => "Monte Alegre do Piauí",
                "lat" => -9.753640,
                "lng" => -45.303699,
                "capital" => 0,
            ),
            array(
                "id" => 2206654,
                "state_id" => 22,
                "city" => "Morro Cabeça no Tempo",
                "lat" => -9.718910,
                "lng" => -43.907200,
                "capital" => 0,
            ),
            array(
                "id" => 2206670,
                "state_id" => 22,
                "city" => "Morro do Chapéu do Piauí",
                "lat" => -3.733370,
                "lng" => -42.302399,
                "capital" => 0,
            ),
            array(
                "id" => 2206696,
                "state_id" => 22,
                "city" => "Murici dos Portelas",
                "lat" => -3.319000,
                "lng" => -42.094002,
                "capital" => 0,
            ),
            array(
                "id" => 2206704,
                "state_id" => 22,
                "city" => "Nazaré do Piauí",
                "lat" => -6.970230,
                "lng" => -42.677299,
                "capital" => 0,
            ),
            array(
                "id" => 2206720,
                "state_id" => 22,
                "city" => "Nazária",
                "lat" => -5.351280,
                "lng" => -42.815300,
                "capital" => 0,
            ),
            array(
                "id" => 2206753,
                "state_id" => 22,
                "city" => "Nossa Senhora de Nazaré",
                "lat" => -4.630190,
                "lng" => -42.173000,
                "capital" => 0,
            ),
            array(
                "id" => 2206803,
                "state_id" => 22,
                "city" => "Nossa Senhora dos Remédios",
                "lat" => -3.975740,
                "lng" => -42.618401,
                "capital" => 0,
            ),
            array(
                "id" => 2206902,
                "state_id" => 22,
                "city" => "Novo Oriente do Piauí",
                "lat" => -6.449010,
                "lng" => -41.926102,
                "capital" => 0,
            ),
            array(
                "id" => 2206951,
                "state_id" => 22,
                "city" => "Novo Santo Antônio",
                "lat" => -5.287490,
                "lng" => -41.932499,
                "capital" => 0,
            ),
            array(
                "id" => 2207009,
                "state_id" => 22,
                "city" => "Oeiras",
                "lat" => -7.019150,
                "lng" => -42.128300,
                "capital" => 0,
            ),
            array(
                "id" => 2207108,
                "state_id" => 22,
                "city" => "Olho D'Água do Piauí",
                "lat" => -5.841250,
                "lng" => -42.559399,
                "capital" => 0,
            ),
            array(
                "id" => 2207207,
                "state_id" => 22,
                "city" => "Padre Marcos",
                "lat" => -7.351010,
                "lng" => -40.899700,
                "capital" => 0,
            ),
            array(
                "id" => 2207306,
                "state_id" => 22,
                "city" => "Paes Landim",
                "lat" => -7.773750,
                "lng" => -42.247398,
                "capital" => 0,
            ),
            array(
                "id" => 2207355,
                "state_id" => 22,
                "city" => "Pajeú do Piauí",
                "lat" => -7.855080,
                "lng" => -42.824799,
                "capital" => 0,
            ),
            array(
                "id" => 2207405,
                "state_id" => 22,
                "city" => "Palmeira do Piauí",
                "lat" => -8.730760,
                "lng" => -44.246601,
                "capital" => 0,
            ),
            array(
                "id" => 2207504,
                "state_id" => 22,
                "city" => "Palmeirais",
                "lat" => -5.970860,
                "lng" => -43.056000,
                "capital" => 0,
            ),
            array(
                "id" => 2207553,
                "state_id" => 22,
                "city" => "Paquetá",
                "lat" => -7.103030,
                "lng" => -41.700001,
                "capital" => 0,
            ),
            array(
                "id" => 2207603,
                "state_id" => 22,
                "city" => "Parnaguá",
                "lat" => -10.216600,
                "lng" => -44.630001,
                "capital" => 0,
            ),
            array(
                "id" => 2207702,
                "state_id" => 22,
                "city" => "Parnaíba",
                "lat" => -2.905850,
                "lng" => -41.775398,
                "capital" => 0,
            ),
            array(
                "id" => 2207751,
                "state_id" => 22,
                "city" => "Passagem Franca do Piauí",
                "lat" => -5.860360,
                "lng" => -42.443600,
                "capital" => 0,
            ),
            array(
                "id" => 2207777,
                "state_id" => 22,
                "city" => "Patos do Piauí",
                "lat" => -7.672310,
                "lng" => -41.240799,
                "capital" => 0,
            ),
            array(
                "id" => 2207793,
                "state_id" => 22,
                "city" => "Pau D'Arco do Piauí",
                "lat" => -5.260720,
                "lng" => -42.390800,
                "capital" => 0,
            ),
            array(
                "id" => 2207801,
                "state_id" => 22,
                "city" => "Paulistana",
                "lat" => -8.134360,
                "lng" => -41.143101,
                "capital" => 0,
            ),
            array(
                "id" => 2207850,
                "state_id" => 22,
                "city" => "Pavussu",
                "lat" => -7.960590,
                "lng" => -43.228401,
                "capital" => 0,
            ),
            array(
                "id" => 2207900,
                "state_id" => 22,
                "city" => "Pedro II",
                "lat" => -4.425850,
                "lng" => -41.448200,
                "capital" => 0,
            ),
            array(
                "id" => 2207934,
                "state_id" => 22,
                "city" => "Pedro Laurentino",
                "lat" => -8.068070,
                "lng" => -42.284698,
                "capital" => 0,
            ),
            array(
                "id" => 2207959,
                "state_id" => 22,
                "city" => "Nova Santa Rita",
                "lat" => -8.097070,
                "lng" => -42.047100,
                "capital" => 0,
            ),
            array(
                "id" => 2208007,
                "state_id" => 22,
                "city" => "Picos",
                "lat" => -7.077210,
                "lng" => -41.466999,
                "capital" => 0,
            ),
            array(
                "id" => 2208106,
                "state_id" => 22,
                "city" => "Pimenteiras",
                "lat" => -6.238390,
                "lng" => -41.411301,
                "capital" => 0,
            ),
            array(
                "id" => 2208205,
                "state_id" => 22,
                "city" => "Pio IX",
                "lat" => -6.830020,
                "lng" => -40.608299,
                "capital" => 0,
            ),
            array(
                "id" => 2208304,
                "state_id" => 22,
                "city" => "Piracuruca",
                "lat" => -3.933350,
                "lng" => -41.708801,
                "capital" => 0,
            ),
            array(
                "id" => 2208403,
                "state_id" => 22,
                "city" => "Piripiri",
                "lat" => -4.271570,
                "lng" => -41.771599,
                "capital" => 0,
            ),
            array(
                "id" => 2208502,
                "state_id" => 22,
                "city" => "Porto",
                "lat" => -3.888150,
                "lng" => -42.699799,
                "capital" => 0,
            ),
            array(
                "id" => 2208551,
                "state_id" => 22,
                "city" => "Porto Alegre do Piauí",
                "lat" => -6.964230,
                "lng" => -44.183701,
                "capital" => 0,
            ),
            array(
                "id" => 2208601,
                "state_id" => 22,
                "city" => "Prata do Piauí",
                "lat" => -5.672650,
                "lng" => -42.204601,
                "capital" => 0,
            ),
            array(
                "id" => 2208650,
                "state_id" => 22,
                "city" => "Queimada Nova",
                "lat" => -8.570640,
                "lng" => -41.410599,
                "capital" => 0,
            ),
            array(
                "id" => 2208700,
                "state_id" => 22,
                "city" => "Redenção do Gurguéia",
                "lat" => -9.479370,
                "lng" => -44.581100,
                "capital" => 0,
            ),
            array(
                "id" => 2208809,
                "state_id" => 22,
                "city" => "Regeneração",
                "lat" => -6.231150,
                "lng" => -42.684200,
                "capital" => 0,
            ),
            array(
                "id" => 2208858,
                "state_id" => 22,
                "city" => "Riacho Frio",
                "lat" => -10.124400,
                "lng" => -44.950298,
                "capital" => 0,
            ),
            array(
                "id" => 2208874,
                "state_id" => 22,
                "city" => "Ribeira do Piauí",
                "lat" => -7.690280,
                "lng" => -42.712799,
                "capital" => 0,
            ),
            array(
                "id" => 2208908,
                "state_id" => 22,
                "city" => "Ribeiro Gonçalves",
                "lat" => -7.556510,
                "lng" => -45.244701,
                "capital" => 0,
            ),
            array(
                "id" => 2209005,
                "state_id" => 22,
                "city" => "Rio Grande do Piauí",
                "lat" => -7.780290,
                "lng" => -43.136902,
                "capital" => 0,
            ),
            array(
                "id" => 2209104,
                "state_id" => 22,
                "city" => "Santa Cruz do Piauí",
                "lat" => -7.178500,
                "lng" => -41.760899,
                "capital" => 0,
            ),
            array(
                "id" => 2209153,
                "state_id" => 22,
                "city" => "Santa Cruz dos Milagres",
                "lat" => -5.805810,
                "lng" => -41.950600,
                "capital" => 0,
            ),
            array(
                "id" => 2209203,
                "state_id" => 22,
                "city" => "Santa Filomena",
                "lat" => -9.112280,
                "lng" => -45.911598,
                "capital" => 0,
            ),
            array(
                "id" => 2209302,
                "state_id" => 22,
                "city" => "Santa Luz",
                "lat" => -8.948800,
                "lng" => -44.129601,
                "capital" => 0,
            ),
            array(
                "id" => 2209351,
                "state_id" => 22,
                "city" => "Santana do Piauí",
                "lat" => -6.946960,
                "lng" => -41.517799,
                "capital" => 0,
            ),
            array(
                "id" => 2209377,
                "state_id" => 22,
                "city" => "Santa Rosa do Piauí",
                "lat" => -6.795810,
                "lng" => -42.281399,
                "capital" => 0,
            ),
            array(
                "id" => 2209401,
                "state_id" => 22,
                "city" => "Santo Antônio de Lisboa",
                "lat" => -6.986760,
                "lng" => -41.225201,
                "capital" => 0,
            ),
            array(
                "id" => 2209450,
                "state_id" => 22,
                "city" => "Santo Antônio dos Milagres",
                "lat" => -6.046470,
                "lng" => -42.712299,
                "capital" => 0,
            ),
            array(
                "id" => 2209500,
                "state_id" => 22,
                "city" => "Santo Inácio do Piauí",
                "lat" => -7.420720,
                "lng" => -41.906300,
                "capital" => 0,
            ),
            array(
                "id" => 2209559,
                "state_id" => 22,
                "city" => "São Braz do Piauí",
                "lat" => -9.057970,
                "lng" => -43.007599,
                "capital" => 0,
            ),
            array(
                "id" => 2209609,
                "state_id" => 22,
                "city" => "São Félix do Piauí",
                "lat" => -5.934850,
                "lng" => -42.117199,
                "capital" => 0,
            ),
            array(
                "id" => 2209658,
                "state_id" => 22,
                "city" => "São Francisco de Assis do Piauí",
                "lat" => -8.235990,
                "lng" => -41.687302,
                "capital" => 0,
            ),
            array(
                "id" => 2209708,
                "state_id" => 22,
                "city" => "São Francisco do Piauí",
                "lat" => -7.246300,
                "lng" => -42.541000,
                "capital" => 0,
            ),
            array(
                "id" => 2209757,
                "state_id" => 22,
                "city" => "São Gonçalo do Gurguéia",
                "lat" => -10.031900,
                "lng" => -45.309200,
                "capital" => 0,
            ),
            array(
                "id" => 2209807,
                "state_id" => 22,
                "city" => "São Gonçalo do Piauí",
                "lat" => -5.993930,
                "lng" => -42.709499,
                "capital" => 0,
            ),
            array(
                "id" => 2209856,
                "state_id" => 22,
                "city" => "São João da Canabrava",
                "lat" => -6.812030,
                "lng" => -41.341499,
                "capital" => 0,
            ),
            array(
                "id" => 2209872,
                "state_id" => 22,
                "city" => "São João da Fronteira",
                "lat" => -3.954970,
                "lng" => -41.256901,
                "capital" => 0,
            ),
            array(
                "id" => 2209906,
                "state_id" => 22,
                "city" => "São João da Serra",
                "lat" => -5.510810,
                "lng" => -41.892300,
                "capital" => 0,
            ),
            array(
                "id" => 2209955,
                "state_id" => 22,
                "city" => "São João da Varjota",
                "lat" => -6.940820,
                "lng" => -41.888901,
                "capital" => 0,
            ),
            array(
                "id" => 2209971,
                "state_id" => 22,
                "city" => "São João do Arraial",
                "lat" => -3.818600,
                "lng" => -42.445900,
                "capital" => 0,
            ),
            array(
                "id" => 2210003,
                "state_id" => 22,
                "city" => "São João do Piauí",
                "lat" => -8.354660,
                "lng" => -42.255901,
                "capital" => 0,
            ),
            array(
                "id" => 2210052,
                "state_id" => 22,
                "city" => "São José do Divino",
                "lat" => -3.814110,
                "lng" => -41.830799,
                "capital" => 0,
            ),
            array(
                "id" => 2210102,
                "state_id" => 22,
                "city" => "São José do Peixe",
                "lat" => -7.485540,
                "lng" => -42.567200,
                "capital" => 0,
            ),
            array(
                "id" => 2210201,
                "state_id" => 22,
                "city" => "São José do Piauí",
                "lat" => -6.871940,
                "lng" => -41.473099,
                "capital" => 0,
            ),
            array(
                "id" => 2210300,
                "state_id" => 22,
                "city" => "São Julião",
                "lat" => -7.083910,
                "lng" => -40.824600,
                "capital" => 0,
            ),
            array(
                "id" => 2210359,
                "state_id" => 22,
                "city" => "São Lourenço do Piauí",
                "lat" => -9.164630,
                "lng" => -42.549599,
                "capital" => 0,
            ),
            array(
                "id" => 2210375,
                "state_id" => 22,
                "city" => "São Luis do Piauí",
                "lat" => -6.819360,
                "lng" => -41.317501,
                "capital" => 0,
            ),
            array(
                "id" => 2210383,
                "state_id" => 22,
                "city" => "São Miguel da Baixa Grande",
                "lat" => -5.856460,
                "lng" => -42.193401,
                "capital" => 0,
            ),
            array(
                "id" => 2210391,
                "state_id" => 22,
                "city" => "São Miguel do Fidalgo",
                "lat" => -7.597130,
                "lng" => -42.367599,
                "capital" => 0,
            ),
            array(
                "id" => 2210409,
                "state_id" => 22,
                "city" => "São Miguel do Tapuio",
                "lat" => -5.497290,
                "lng" => -41.316502,
                "capital" => 0,
            ),
            array(
                "id" => 2210508,
                "state_id" => 22,
                "city" => "São Pedro do Piauí",
                "lat" => -5.920780,
                "lng" => -42.719200,
                "capital" => 0,
            ),
            array(
                "id" => 2210607,
                "state_id" => 22,
                "city" => "São Raimundo Nonato",
                "lat" => -9.012410,
                "lng" => -42.698700,
                "capital" => 0,
            ),
            array(
                "id" => 2210623,
                "state_id" => 22,
                "city" => "Sebastião Barros",
                "lat" => -10.817000,
                "lng" => -44.833698,
                "capital" => 0,
            ),
            array(
                "id" => 2210631,
                "state_id" => 22,
                "city" => "Sebastião Leal",
                "lat" => -7.568030,
                "lng" => -44.060001,
                "capital" => 0,
            ),
            array(
                "id" => 2210656,
                "state_id" => 22,
                "city" => "Sigefredo Pacheco",
                "lat" => -4.916650,
                "lng" => -41.731098,
                "capital" => 0,
            ),
            array(
                "id" => 2210706,
                "state_id" => 22,
                "city" => "Simões",
                "lat" => -7.591090,
                "lng" => -40.813702,
                "capital" => 0,
            ),
            array(
                "id" => 2210805,
                "state_id" => 22,
                "city" => "Simplício Mendes",
                "lat" => -7.852940,
                "lng" => -41.907501,
                "capital" => 0,
            ),
            array(
                "id" => 2210904,
                "state_id" => 22,
                "city" => "Socorro do Piauí",
                "lat" => -7.867730,
                "lng" => -42.492199,
                "capital" => 0,
            ),
            array(
                "id" => 2210938,
                "state_id" => 22,
                "city" => "Sussuapara",
                "lat" => -7.036870,
                "lng" => -41.376701,
                "capital" => 0,
            ),
            array(
                "id" => 2210953,
                "state_id" => 22,
                "city" => "Tamboril do Piauí",
                "lat" => -8.409370,
                "lng" => -42.921101,
                "capital" => 0,
            ),
            array(
                "id" => 2210979,
                "state_id" => 22,
                "city" => "Tanque do Piauí",
                "lat" => -6.597870,
                "lng" => -42.279499,
                "capital" => 0,
            ),
            array(
                "id" => 2211001,
                "state_id" => 22,
                "city" => "Teresina",
                "lat" => -5.091940,
                "lng" => -42.803398,
                "capital" => 1,
            ),
            array(
                "id" => 2211100,
                "state_id" => 22,
                "city" => "União",
                "lat" => -4.585710,
                "lng" => -42.858299,
                "capital" => 0,
            ),
            array(
                "id" => 2211209,
                "state_id" => 22,
                "city" => "Uruçuí",
                "lat" => -7.239440,
                "lng" => -44.557701,
                "capital" => 0,
            ),
            array(
                "id" => 2211308,
                "state_id" => 22,
                "city" => "Valença do Piauí",
                "lat" => -6.403010,
                "lng" => -41.737499,
                "capital" => 0,
            ),
            array(
                "id" => 2211357,
                "state_id" => 22,
                "city" => "Várzea Branca",
                "lat" => -9.238000,
                "lng" => -42.969200,
                "capital" => 0,
            ),
            array(
                "id" => 2211407,
                "state_id" => 22,
                "city" => "Várzea Grande",
                "lat" => -6.548990,
                "lng" => -42.248001,
                "capital" => 0,
            ),
            array(
                "id" => 2211506,
                "state_id" => 22,
                "city" => "Vera Mendes",
                "lat" => -7.597480,
                "lng" => -41.467300,
                "capital" => 0,
            ),
            array(
                "id" => 2211605,
                "state_id" => 22,
                "city" => "Vila Nova do Piauí",
                "lat" => -7.132720,
                "lng" => -40.934502,
                "capital" => 0,
            ),
            array(
                "id" => 2211704,
                "state_id" => 22,
                "city" => "Wall Ferraz",
                "lat" => -7.231510,
                "lng" => -41.904999,
                "capital" => 0,
            ),
        );


        foreach ($cities as $registro) {

            City::create($registro);
        }
    }
}
